version: "3.9"
services:
  api:
    # I choose the LTS version
    image: node:18.17
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    command: yarn dev
